Update test_requests_mac.yml

diff --git a/.github/workflows/test_requests_mac.yml b/.github/workflows/test_requests_mac.yml
--- a/.github/workflows/test_requests_mac.yml
+++ b/.github/workflows/test_requests_mac.yml
@@ -38,8 +38,8 @@ jobs:
 
 
 
-    - name: Fail
-      run: exit 1
+    # - name: Fail
+    #   run: exit 1
 
     - name: Get start date time
       run: echo "Starting time $(date +'%Y-%m-%dT%H:%M:%S')"
@@ -58,8 +58,8 @@ jobs:
         # webhook_secret: ${{ secrets.WEB_HOOK_SECRET }}
         # data: ${{ steps.get_changes.outputs.packageJson }}
         # data_type: "scoring"
-        r_time_out: "325"
-        time_out: 340
+        r_time_out: "5"
+        time_out: 10
         
         
       run: |
