Update upload_evaluations.yml

diff --git a/.github/workflows/upload_evaluations.yml b/.github/workflows/upload_evaluations.yml
--- a/.github/workflows/upload_evaluations.yml
+++ b/.github/workflows/upload_evaluations.yml
@@ -74,8 +74,6 @@ jobs:
           python ./tools/code/copy_and_split.py --hub_path "./repo" --tmp_folder ".github/temp_eval"
 
 
-
-
       # Commit so that remote web platform can access 
       # temporary data 
       # --------------------------------------------
@@ -89,9 +87,20 @@ jobs:
           push: true
 
 
+      # Trigger server-side updating and UI deploy
+      # --------------------------------------------
+      # WEBHOOK
+      - name: Invoke deployment hook
+        id: invoke_webhook
+        env:
+          disease_name: ${{ vars.DISEASE_NAME }}
+          webhook_url: ${{ secrets.WEB_HOOK_URL }}
+          webhook_secret: ${{ secrets.WEB_HOOK_SECRET }}
+          data: ${{ steps.get_changes.outputs.packageJson }}
+        
+        run: |
+          python ./tools/code/update_and_clear.py --hub_path "./repo" --tmp_folder ".github/temp_eval"
 
-          
-      
       # # Trigger server-side updating and UI deploy
       # # --------------------------------------------
       # # WEBHOOK
@@ -107,46 +116,59 @@ jobs:
       #   run: |
       #     python ./tools/code/ws_webhook.py
           
-      # - name: trace only
-      #   run: |
-      #     echo "webhook results: ${{ steps.invoke_webhook.outputs.run_results }}"
+      - name: trace only
+        run: |
+          echo "webhook results: ${{ steps.invoke_webhook.outputs.run_results }}"
 
-      # # SUCCESSFUL RUN
-      # # --------------------------------------------
-      # - name: Successful run
-      #   if: ${{ fromJSON(steps.invoke_webhook.outputs.run_results).status == 'success'}}
-      #   env:
-      #     wh_response:  ${{ steps.invoke_webhook.outputs.run_results }}
-      #   run: |
-      #     echo "UPLOAD SUCCEEDED -  clear djson db"
-      #     python ./tools/code/clear_data_storage.py --storage_type "scoring"
-
-      # # RUN FAILURE
-      # # --------------------------------------------
-      # - name: Some ingestion failed
-      #   if: ${{ fromJSON(steps.invoke_webhook.outputs.run_results).status == 'failure'}}
-      #   env:
-      #     wh_response:  ${{ steps.invoke_webhook.outputs.run_results }}
           
-      #   run: |
-      #     echo "UPLOAD FAILED - Some ingestion failed"
-      #     python ./tools/code/clear_data_storage.py --storage_type "scoring" 
+      # SUCCESSFUL RUN
+      # --------------------------------------------
+      - name: Successful run
+        if: ${{ fromJSON(steps.invoke_webhook.outputs.run_results).status == 'success'}}
+        env:
+          wh_response:  ${{ steps.invoke_webhook.outputs.run_results }}
+        run: |
+          echo "UPLOAD SUCCEEDED -  clear djson db"
+          python ./tools/code/clear_data_storage.py --storage_type "scoring"
 
-      # # ERROR RUN
-      # # --------------------------------------------
-      # - name: Error
-      #   if: ${{ steps.invoke_webhook.outputs.run_results.status == 'error'}}
-      #   run: |
-      #     echo "UPLOAD FAILED -  ignore djson db cleaning"
-      #     exit 1
+      # RUN FAILURE
+      # --------------------------------------------
+      - name: Some ingestion failed
+        if: ${{ fromJSON(steps.invoke_webhook.outputs.run_results).status == 'failure'}}
+        env:
+          wh_response:  ${{ steps.invoke_webhook.outputs.run_results }}
+          
+        run: |
+          echo "UPLOAD FAILED - Some ingestion failed"
+          python ./tools/code/clear_data_storage.py --storage_type "scoring" 
 
-      # # Final commit
-      # # --------------------------------------------
-      # - name: Commit changes
-      #   if: ${{ fromJSON(steps.invoke_webhook.outputs.run_results).status == 'failure' || fromJSON(steps.invoke_webhook.outputs.run_results).status == 'success' }}
-      #   uses: EndBug/add-and-commit@v7
-      #   with: 
-      #     cwd: './repo'
-      #     message: "Update metadata db json"
-      #     default_author: github_actions
-      #     push: true
+      # ERROR RUN
+      # --------------------------------------------
+      - name: Error
+        if: ${{ steps.invoke_webhook.outputs.run_results.status == 'error'}}
+        run: |
+          echo "UPLOAD ERROR - ignore json db cleaning"
+
+      # Final commit
+      # This commit is anyway needed to commit 
+      # the temporary data folder cleaning
+      # -------------------------------------------------------
+      - name: Commit changes
+        # if: ${{ fromJSON(steps.invoke_webhook.outputs.run_results).status == 'failure' || fromJSON(steps.invoke_webhook.outputs.run_results).status == 'success' }}
+        uses: EndBug/add-and-commit@v7
+        with: 
+          cwd: './repo'
+          message: "Update metadata db json"
+          default_author: github_actions
+          push: true
+
+      
+      # Be sure to exit 1 on error or failure
+      # --------------------------------------------
+      - name: Error
+        if: ${{ fromJSON(steps.invoke_webhook.outputs.run_results).status == 'failure' || fromJSON(steps.invoke_webhook.outputs.run_results).status == 'error' }}
+        # if: ${{ steps.invoke_webhook.outputs.run_results.status == 'error'}}
+        run: |
+          echo "Error or some ingestion failed"
+          exit 1
+
