Update upload_evaluations.yml

diff --git a/.github/workflows/upload_evaluations.yml b/.github/workflows/upload_evaluations.yml
--- a/.github/workflows/upload_evaluations.yml
+++ b/.github/workflows/upload_evaluations.yml
@@ -13,14 +13,14 @@ on:
   
 jobs:
   scheduled-submit:
-    if: ${{ github.event.workflow_run.conclusion == 'success' && github.repository_owner == 'european-modelling-hubs' }}
+    # if: ${{ github.event.workflow_run.conclusion == 'success' && github.repository_owner == 'european-modelling-hubs' }}
     runs-on: ubuntu-latest
     
     steps:
       # Introduce some delay to complete DB write 
-      - name: Sleep for 90 seconds
-        run: sleep 90s
-        shell: bash
+      # - name: Sleep for 90 seconds
+      #   run: sleep 90s
+      #   shell: bash
       
       # Checkout the python tools repo
       # used to authenticate and validate the PR
@@ -29,7 +29,7 @@ jobs:
         uses: actions/checkout@v3
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
-          repository: 'european-modelling-hubs/hub-tools'
+          repository: 'Testing-Forecast-Actions/Testing-Tools'
           ref: 'main'
           path: tools
 
@@ -38,9 +38,16 @@ jobs:
         uses: actions/checkout@v3
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
-          repository: 'european-modelling-hubs/RespiCast-SyndromicIndicators'
+          repository: 'Testing-Forecast-Actions/RespiCast-SyndromicIndicators'
           ref: 'main'
           path: './repo/'
+
+      # eventually install additional packages
+      # installing requests specific version because the one installed with 
+      # the os (2.31.0) can casue issues with timeout scenario
+      - name: Installing python additional packages
+        run: pip install requests==2.32.3
+
           
       # Get the list of changes from a json file 
       - name: Get changes list
@@ -51,74 +58,95 @@ jobs:
           content="${content//'%'/'%25'}"
           content="${content//$'\n'/'%0A'}"
           content="${content//$'\r'/'%0D'}"
-          echo "::set-output name=packageJson::$content"
-          
+          echo "::set-output name=packageJson::$content"          
 
       - run: |
           echo "${{ steps.get_changes.outputs.packageJson }}"
 
-      # eventually install additional packages
-      # installing requests specific version because the one installed with 
-      # the os (2.31.0) can casue issues with timeout scenario
-      - name: Installing python additional packages
-        run: pip install requests==2.32.3
-    
-    
-      # Trigger server-side updating and UI deploy
-      # --------------------------------------------
-      # WEBHOOK
-      - name: Invoke deployment hook
-        id: invoke_webhook
+
+      # Prepare uploading eventually splitting source file
+      # Prepare
+      - name: Prepare Uploadings
+        id: prepare_uploadings
         env:
-          disease_name: ${{ vars.DISEASE_NAME }}
-          webhook_url: ${{ secrets.WEB_HOOK_URL }}
-          webhook_secret: ${{ secrets.WEB_HOOK_SECRET }}
           data: ${{ steps.get_changes.outputs.packageJson }}
-          data_type: "scoring"
-
         run: |
-          python ./tools/code/ws_webhook.py
-          
-      - name: trace only
-        run: |
-          echo "webhook results: ${{ steps.invoke_webhook.outputs.run_results }}"
+          python ./tools/code/copy_and_split.py --hub_path "./repo" --tmp_folder ".github/temp_eval"
 
-      # SUCCESSFUL RUN
-      # --------------------------------------------
-      - name: Successful run
-        if: ${{ fromJSON(steps.invoke_webhook.outputs.run_results).status == 'success'}}
-        env:
-          wh_response:  ${{ steps.invoke_webhook.outputs.run_results }}
-        run: |
-          echo "UPLOAD SUCCEEDED -  clear djson db"
-          python ./tools/code/clear_data_storage.py --storage_type "scoring"
 
-      # RUN FAILURE
-      # --------------------------------------------
-      - name: Some ingestion failed
-        if: ${{ fromJSON(steps.invoke_webhook.outputs.run_results).status == 'failure'}}
-        env:
-          wh_response:  ${{ steps.invoke_webhook.outputs.run_results }}
-          
-        run: |
-          echo "UPLOAD FAILED - Some ingestion failed"
-          python ./tools/code/clear_data_storage.py --storage_type "scoring" 
 
-      # ERROR RUN
-      # --------------------------------------------
-      - name: Error
-        if: ${{ steps.invoke_webhook.outputs.run_results.status == 'error'}}
-        run: |
-          echo "UPLOAD FAILED -  ignore djson db cleaning"
-          exit 1
 
-      # Final commit
+      # Commit so that remote web platform can access 
+      # temporary data 
       # --------------------------------------------
       - name: Commit changes
-        if: ${{ fromJSON(steps.invoke_webhook.outputs.run_results).status == 'failure' || fromJSON(steps.invoke_webhook.outputs.run_results).status == 'success' }}
+        # if: ${{ fromJSON(steps.invoke_webhook.outputs.run_results).status == 'failure' || fromJSON(steps.invoke_webhook.outputs.run_results).status == 'success' }}
         uses: EndBug/add-and-commit@v7
         with: 
           cwd: './repo'
           message: "Update metadata db json"
           default_author: github_actions
           push: true
+
+
+
+          
+      
+      # # Trigger server-side updating and UI deploy
+      # # --------------------------------------------
+      # # WEBHOOK
+      # - name: Invoke deployment hook
+      #   id: invoke_webhook
+      #   env:
+      #     disease_name: ${{ vars.DISEASE_NAME }}
+      #     webhook_url: ${{ secrets.WEB_HOOK_URL }}
+      #     webhook_secret: ${{ secrets.WEB_HOOK_SECRET }}
+      #     data: ${{ steps.get_changes.outputs.packageJson }}
+      #     data_type: "scoring"
+
+      #   run: |
+      #     python ./tools/code/ws_webhook.py
+          
+      # - name: trace only
+      #   run: |
+      #     echo "webhook results: ${{ steps.invoke_webhook.outputs.run_results }}"
+
+      # # SUCCESSFUL RUN
+      # # --------------------------------------------
+      # - name: Successful run
+      #   if: ${{ fromJSON(steps.invoke_webhook.outputs.run_results).status == 'success'}}
+      #   env:
+      #     wh_response:  ${{ steps.invoke_webhook.outputs.run_results }}
+      #   run: |
+      #     echo "UPLOAD SUCCEEDED -  clear djson db"
+      #     python ./tools/code/clear_data_storage.py --storage_type "scoring"
+
+      # # RUN FAILURE
+      # # --------------------------------------------
+      # - name: Some ingestion failed
+      #   if: ${{ fromJSON(steps.invoke_webhook.outputs.run_results).status == 'failure'}}
+      #   env:
+      #     wh_response:  ${{ steps.invoke_webhook.outputs.run_results }}
+          
+      #   run: |
+      #     echo "UPLOAD FAILED - Some ingestion failed"
+      #     python ./tools/code/clear_data_storage.py --storage_type "scoring" 
+
+      # # ERROR RUN
+      # # --------------------------------------------
+      # - name: Error
+      #   if: ${{ steps.invoke_webhook.outputs.run_results.status == 'error'}}
+      #   run: |
+      #     echo "UPLOAD FAILED -  ignore djson db cleaning"
+      #     exit 1
+
+      # # Final commit
+      # # --------------------------------------------
+      # - name: Commit changes
+      #   if: ${{ fromJSON(steps.invoke_webhook.outputs.run_results).status == 'failure' || fromJSON(steps.invoke_webhook.outputs.run_results).status == 'success' }}
+      #   uses: EndBug/add-and-commit@v7
+      #   with: 
+      #     cwd: './repo'
+      #     message: "Update metadata db json"
+      #     default_author: github_actions
+      #     push: true
